name: disaster_response
channels:
  - anaconda
  - conda-forge
dependencies:
  - flask=2.2.2
  - jupyter=1.0.0
  - matplotlib=3.8.0
  - nltk=3.8.1
  - numpy=1.26.0
  - pandas=2.1.1
  - plotly=5.9.0
  - python=3.12.4
  - scikit-learn=1.3.0
  - seaborn=0.12.2
